### ISSUE TITLE
The examples are broken

### ISSUE THREAD

**Issue by LacikIgor** [nickzuber/material-paper#1]
Hi,

wanted to take a look at the examples.

After cloning, I ran `npm i`, nevertheless, saw a missing **babel-cli** error. Installed **babel-cli**. The same with **express**. 

Now stuck at **node-jsx** - even after installing both **node-jsx** and **node-jsx-babel**, I still have these problems.

Keep up the good work.

```
> material-paper@0.0.7 serve c:\Users\***\workspace\react-components\material-paper
> babel ./src --out-dir ./build && gulp examples && node examples/app

src\index.js -> build\index.js
src\lib\classes\animate.js -> build\lib\classes\animate.js
src\lib\classes\burst.js -> build\lib\classes\burst.js
src\lib\classes\componentdidmount.js -> build\lib\classes\componentdidmount.js
src\lib\classes\createburst.js -> build\lib\classes\createburst.js
src\lib\classes\flagchildren.js -> build\lib\classes\flagchildren.js
src\lib\classes\handleclick.js -> build\lib\classes\handleclick.js
src\lib\classes\liftdown.js -> build\lib\classes\liftdown.js
src\lib\classes\liftup.js -> build\lib\classes\liftup.js
src\lib\classes\onmouseout.js -> build\lib\classes\onmouseout.js
src\lib\classes\onmouseover.js -> build\lib\classes\onmouseover.js
src\lib\classes\onmouseup.js -> build\lib\classes\onmouseup.js
src\lib\classes\seteventhandler.js -> build\lib\classes\seteventhandler.js
src\lib\paper.jsx -> build\lib\paper.js
src\lib\styles\paper.stl.js -> build\lib\styles\paper.stl.js
src\lib\styles\utils.stl.js -> build\lib\styles\utils.stl.js
src\lib\utils\methods.js -> build\lib\utils\methods.js
[08:43:31] Using gulpfile c:\Users\***\workspace\react-components\material-paper\gulpfile.js
[08:43:31] Starting 'examples'...
[08:43:32] Finished 'examples' after 525 ms
[08:43:33] Version: webpack 1.15.0
                  Asset    Size  Chunks             Chunk Names
9e297cf1ab40578c9dda.js  798 kB       0  [emitted]  main

ERROR in ./examples/modules/Index.jsx
Module not found: Error: Cannot resolve module 'material-paper' in c:\Users\***\workspace\react-components\material-paper\examples\modules
 @ ./examples/modules/Index.jsx 15:24-49
module.js:471
    throw err;
    ^

Error: Cannot find module 'node-jsx'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (c:\Users\***\workspace\react-components\material-paper\examples\app.js:18:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "serve"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! material-paper@0.0.7 serve: `babel ./src --out-dir ./build && gulp examples && node examples/app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the material-paper@0.0.7 serve script 'babel ./src --out-dir ./build && gulp examples && node examples/app'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the material-paper package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel ./src --out-dir ./build && gulp examples && node examples/app
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs material-paper
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls material-paper
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Users\***\workspace\react-components\material-paper\npm-debug.log
```

**Comment by nickzuber** [comment]
Thanks for the issue! Yeah I haven't touched this project in over a year, I bet some of these dependencies are really out of date 😅 

Especially with the examples, I'm sure there are simpler and more reliable ways around now to spin up quick local servers than what I have currently. I'll try to take a look at this later!
